### PR TITLE
Upload my codes.

### PR DESCRIPTION
**Pull request by liewchooichin**
Just uploaded my codes. See notes in README.
Added the Jackson ObjectMapper dependency in pom.xml. Need to update the pom.xml.

### CODE REVIEW

**Comment by liewchooichin** [comment]
Add in DataLoader to load data post construct.

**Comment by liewchooichin** [comment]
Strange. I do pull request once more. Don't know whether the request has been processed or not?

**Comment by liewchooichin** [comment]
Move the DataLoader to config. Update readme.

**Review by agentjimlam — COMMENTED** [review]
Oh I see, so ApiController.java you wrote web request handling paths for 
"datamall/stops"
"datamall/services"
"datamall/routes"

then in the other sub-controllers like AppBusStopController.java you gave them request paths that start with "/app", like

"/app/services"
"/app/stops"
"/app/routes"

**Review by agentjimlam — COMMENTED** [review]
The maven-surefire-plugin should be fine to add/approve, as adding these plugins manually is for full control over their configuration, and you configured it to continue tests cases even when some fail. In class, when testing a file with multiple tests, it stops tests upon hitting an error. This makes testing more convenient! 

The maven-surefire-report-plugin is also okay, it generates the report based on test results. In class we run "mvn surefire-report:report" and it generates a report

**Review by agentjimlam — COMMENTED** [review]
There's this bunch of Jackson dependencies added that is not necessary. Spring-boot-starter and spring-boot-starter-web dependency alr includes these Jackson modules

It's like a duplicate right now, can lead to dependency version conflicts

To comment out

**Review by agentjimlam — APPROVED** [review]
Code Review done. Approving merge

**Pull request merged**
